[package]
name = "sgx_unwind"
version = "0.0.1"
authors = ["Baidu"]
build = "build.rs"
repository = "https://github.com/baidu/rust-sgx-sdk"
license-file = "LICENSE"
documentation = "https://dingelish.github.io/"
description = "Rust SGX SDK provides the ability to write Intel SGX applications in Rust Programming Language."
edition = "2018"
exclude = ["libunwind/autom4te.cache/*",]

[lib]
name = "sgx_unwind"
path = "lib.rs"
test = false
bench = false
doc = false

[build-dependencies]
sgx_build_helper = { path = "../sgx_build_helper" }

[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_trts = { path = "../sgx_trts" }
