[package]
name = "Hugememsampleenclave"
version = "0.9.6"
authors = ["Baidu"]

[lib]
name = "hugememsampleenclave"
crate-type = ["staticlib"]

[features]
default = []

[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_types = { path = "../../../sgx_types" }
sgx_tstd = { path = "../../../sgx_tstd" }
