[package]
name = "pcl-user"
version = "0.1.0"
authors = ["Yu Ding <dingyu02@baidu.com>"]
build = "build.rs"

[dependencies]
chrono      = "0.4.5"
webpki      = "0.21"
rustls      = { version = "0.16", features = ["dangerous_configuration"] }
itertools   = "*"
sgx_types   = { rev = "v1.0.8", git = "https://github.com/baidu/rust-sgx-sdk" }
base64      = "0.9.2"
serde_json  = "1.0"
num-bigint  = "*"
bit-vec     = "*"
hex         = "*"
ue_send_recv= { path = "ue_send_recv" }

[build-dependencies]
itertools   = "*"

[patch.'https://github.com/baidu/rust-sgx-sdk.git']
sgx_types = { path = "../../../sgx_types" }
sgx_urts = { path = "../../../sgx_urts" }
