[package]
name = "Sealdatasampleenclave"
version = "0.9.5"
authors = ["Baidu"]

[lib]
name = "sealdatasampleenclave"
crate-type = ["staticlib"]

[features]
default = []

[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_types = { path = "../../../sgx_types" }
sgx_tseal = { path = "../../../sgx_tseal" }
sgx_tstd = { path = "../../../sgx_tstd" }
sgx_rand = { path = "../../../sgx_rand" }
