[package]
name = "sgx_urts"
version = "1.1.6"
authors = ["The Teaclave Authors"]
repository = "https://github.com/apache/teaclave-sgx-sdk"
license-file = "LICENSE"
documentation = "https://teaclave.apache.org/sgx-sdk-docs/"
description = "Rust SGX SDK provides the ability to write Intel SGX applications in Rust Programming Language."
edition = "2021"

[lib]
name = "sgx_urts"
crate-type = ["rlib"]

[features]
default = []
global_init = ["global_exit"]
global_exit = ["global_init"]

[dependencies]
sgx_types = { path = "../sgx_types" }
libc = "0.2"
