[package]
name = "sgx_urts"
version = "1.1.0"
authors = ["The Teaclave Authors"]
repository = "https://github.com/baidu/rust-sgx-sdk"
license-file = "LICENSE"
documentation = "https://dingelish.github.io/"
description = "Rust SGX SDK provides the ability to write Intel SGX applications in Rust Programming Language."
edition = "2018"

[lib]
name = "sgx_urts"
crate-type = ["rlib"]

[features]
default = []
global_init = []
global_exit = []


[dependencies]
sgx_types = { path = "../sgx_types" }
libc = "0.2.40"
