[package]
name = "sgx_tstd"
version = "1.1.0"
authors = ["Baidu"]
build = "build.rs"
repository = "https://github.com/baidu/rust-sgx-sdk"
license-file = "LICENSE"
documentation = "https://dingelish.github.io/"
description = "Rust SGX SDK provides the ability to write Intel SGX applications in Rust Programming Language."
edition = "2018"

[lib]
name = "sgx_tstd"
crate-type = ["rlib"]

[features]
default = ["stdio"]
backtrace = ["stdio"]
stdio = []
net = []
pipe = []
thread = []
untrusted_fs = []
untrusted_time = []

[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_types = { path = "../sgx_types" }
sgx_libc = { path = "../sgx_libc" }
sgx_trts = { path = "../sgx_trts" }
sgx_alloc = { path = "../sgx_alloc" }
sgx_tseal = { path = "../sgx_tseal" }
sgx_tprotected_fs = { path = "../sgx_tprotected_fs" }
sgx_backtrace_sys = { path = "../sgx_backtrace_sys" }
sgx_demangle = { path = "../sgx_demangle" }
sgx_unwind = { path = "../sgx_unwind" }
