[package]
name = "std"
version = "0.0.0"
authors = ["Baidu"]
build = "build.rs"
edition = "2018"

[lib]
name = "std"
path = "../../sgx_tstd/src/lib.rs"
crate-type = ["rlib"]

[features]
default = ["stdio"]
backtrace = ["stdio"]
stdio = []
net = []
pipe = []
untrusted_fs = []
untrusted_time = []

[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_types = { path = "../../sgx_types" }
sgx_libc = { path = "../../sgx_libc" }
sgx_trts = { path = "../../sgx_trts" }
sgx_alloc = { path = "../../sgx_alloc" }
sgx_tseal = { path = "../../sgx_tseal" }
sgx_tprotected_fs = { path = "../../sgx_tprotected_fs" }
sgx_backtrace_sys = { path = "../../sgx_backtrace_sys" }
sgx_demangle = { path = "../../sgx_demangle" }
sgx_unwind = { path = "../../sgx_unwind" }
