[package]
name = "Threadsampleenclave"
version = "0.9.8"
authors = ["Baidu"]

[lib]
name = "threadsampleenclave"
crate-type = ["staticlib"]

[features]
default = []

[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_tstd = { path = "../../../sgx_tstd" }
