[package]
name = "db-server"
version = "0.1.0"
authors = ["webb.shi <bradyjoestar@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"
rocksdb = "0.5"