[package]
name = "sgx_serialize"
version = "1.0.7"
authors = ["Baidu"]

[lib]
name = "sgx_serialize"
path = "../../sgx_serialize/src/lib.rs"
crate-type = ["rlib"]

[features]
default = []

[dependencies]