[package]
name = "ueRA"
version = "1.0.0"
authors = ["The Teaclave Authors"]

[lib]
name = "uera"
crate-type = ["staticlib"]

[features]
default = []

[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_types   = { git = "https://github.com/apache/teaclave-sgx-sdk.git" }
sgx_tstd    = { git = "https://github.com/apache/teaclave-sgx-sdk.git", features = ["net"] }
sgx_tcrypto = { git = "https://github.com/apache/teaclave-sgx-sdk.git" }
sgx_tse     = { git = "https://github.com/apache/teaclave-sgx-sdk.git" }
sgx_rand    = { git = "https://github.com/apache/teaclave-sgx-sdk.git" }

[dependencies]
chrono      = { git = "https://github.com/mesalock-linux/chrono-sgx" }
webpki      = { git = "https://github.com/mesalock-linux/webpki", branch = "mesalock_sgx" }
base64      = { git = "https://github.com/mesalock-linux/rust-base64-sgx" }
yasna       = { git = "https://github.com/mesalock-linux/yasna.rs-sgx", features = ["bit-vec", "num-bigint", "chrono"] }
num-bigint  = { git = "https://github.com/mesalock-linux/num-bigint-sgx" }
bit-vec     = { version = "*", default-features = false}
httparse    = { version = "1.3.2", default-features=false }
itertools   = { version = "0.8" , default-features = false, features = []}
rustls      = { git = "https://github.com/mesalock-linux/rustls", branch = "mesalock_sgx" }
webpki-roots= { git = "https://github.com/mesalock-linux/webpki-roots", branch = "mesalock_sgx" }

# Comment out these following lines to use rust-sgx-sdk from git
[patch.'https://github.com/apache/teaclave-sgx-sdk.git']
sgx_alloc = { path = "../../../../sgx_alloc" }
sgx_backtrace = { path = "../../../../sgx_backtrace" }
sgx_backtrace_sys = { path = "../../../../sgx_backtrace_sys" }
sgx_build_helper = { path = "../../../../sgx_build_helper" }
sgx_cov = { path = "../../../../sgx_cov" }
sgx_crypto_helper = { path = "../../../../sgx_crypto_helper" }
sgx_demangle = { path = "../../../../sgx_demangle" }
sgx_libc = { path = "../../../../sgx_libc" }
sgx_rand = { path = "../../../../sgx_rand" }
sgx_rand_derive = { path = "../../../../sgx_rand_derive" }
sgx_serialize = { path = "../../../../sgx_serialize" }
sgx_serialize_derive = { path = "../../../../sgx_serialize_derive" }
sgx_serialize_derive_internals = { path = "../../../../sgx_serialize_derive_internals" }
sgx_tcrypto = { path = "../../../../sgx_tcrypto" }
sgx_tcrypto_helper = { path = "../../../../sgx_tcrypto_helper" }
sgx_tdh = { path = "../../../../sgx_tdh" }
sgx_tkey_exchange = { path = "../../../../sgx_tkey_exchange" }
sgx_tprotected_fs = { path = "../../../../sgx_tprotected_fs" }
sgx_trts = { path = "../../../../sgx_trts" }
sgx_tse = { path = "../../../../sgx_tse" }
sgx_tseal = { path = "../../../../sgx_tseal" }
sgx_tstd = { path = "../../../../sgx_tstd" }
sgx_tunittest = { path = "../../../../sgx_tunittest" }
sgx_types = { path = "../../../../sgx_types" }
#sgx_ucrypto = { path = "../../../../sgx_ucrypto" }
sgx_unwind = { path = "../../../../sgx_unwind" }
#sgx_urts = { path = "../../../../sgx_urts" }
