[dependencies]
alloc = {}
panic_unwind = {}
panic_abort = {}

[dependencies.std]
path = "../../../xargo/sgx_tstd"
stage = 1

[dependencies.sgx_rand]
path = "../../../sgx_rand"
stage = 2

[dependencies.sgx_serialize]
path = "../../../sgx_serialize"
stage = 2

[dependencies.sgx_tunittest]
path = "../../../sgx_tunittest"
stage = 2
[patch.crates-io]
libc = { git = "https://github.com/mesalock-linux/libc-sgx" }
