[package]
name = "enclave1"
version = "0.9.5"
authors = ["Baidu"]

[lib]
name = "enclave1"
crate-type = ["staticlib"]

[features]
default = []

[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_types = { path = "../../../sgx_types" }

[dependencies]
attestation = {path = "../attestation/"}