[package]
name = "Helloworldsampleenclave"
version = "1.0.0"
authors = ["Baidu"]

[lib]
name = "helloworldsampleenclave"
crate-type = ["staticlib"]

[features]
default = []

[dependencies]
serde       = { path = "../../../third_party/serde-rs/serde/serde" }
serde_derive = { path = "../../../third_party/serde-rs/serde/serde_derive" }
rust-sqlite = { path = "../../../third_party/rust-sqlite3" }

[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_types = { path = "../../../sgx_types" }
sgx_tstd = { path = "../../../sgx_tstd" }
