[package]
name = "sgx_tcrypto_helper"
version = "1.1.0"
authors = ["Baidu"]
repository = "https://github.com/baidu/rust-sgx-sdk"
license-file = "LICENSE"
documentation = "https://dingelish.github.io/"
description = "Rust SGX SDK provides the ability to write Intel SGX applications in Rust Programming Language."
edition = "2018"

[lib]
name = "sgx_tcrypto_helper"
path = "../sgx_crypto_helper/src/lib.rs"
crate-type = ["staticlib","rlib"]

[features]
default = ["mesalock_sgx"]
mesalock_sgx = []

[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_tcrypto = { rev = "v1.1.0", git = "https://github.com/baidu/rust-sgx-sdk.git" }
sgx_tstd    = { rev = "v1.1.0", git = "https://github.com/baidu/rust-sgx-sdk.git" }
sgx_types   = { rev = "v1.1.0", git = "https://github.com/baidu/rust-sgx-sdk.git" }

[dependencies]
serde = { git = "https://github.com/mesalock-linux/serde-sgx" }
serde_derive = { git = "https://github.com/mesalock-linux/serde-sgx" }
itertools = { version = "*", default-features = false }
serde-big-array = { git = "https://github.com/mesalock-linux/serde-big-array-sgx" }

[patch.'https://github.com/baidu/rust-sgx-sdk.git']
sgx_alloc = { path = "../sgx_alloc" }
sgx_backtrace = { path = "../sgx_backtrace" }
sgx_backtrace_sys = { path = "../sgx_backtrace_sys" }
sgx_build_helper = { path = "../sgx_build_helper" }
sgx_cov = { path = "../sgx_cov" }
sgx_crypto_helper = { path = "../sgx_crypto_helper" }
sgx_demangle = { path = "../sgx_demangle" }
sgx_libc = { path = "../sgx_libc" }
sgx_rand = { path = "../sgx_rand" }
sgx_rand_derive = { path = "../sgx_rand_derive" }
sgx_serialize = { path = "../sgx_serialize" }
sgx_serialize_derive = { path = "../sgx_serialize_derive" }
sgx_serialize_derive_internals = { path = "../sgx_serialize_derive_internals" }
sgx_tcrypto = { path = "../sgx_tcrypto" }
sgx_tcrypto_helper = { path = "../sgx_tcrypto_helper" }
sgx_tdh = { path = "../sgx_tdh" }
sgx_tkey_exchange = { path = "../sgx_tkey_exchange" }
sgx_tprotected_fs = { path = "../sgx_tprotected_fs" }
sgx_trts = { path = "../sgx_trts" }
sgx_tse = { path = "../sgx_tse" }
sgx_tseal = { path = "../sgx_tseal" }
sgx_tservice = { path = "../sgx_tservice" }
sgx_tstd = { path = "../sgx_tstd" }
sgx_tunittest = { path = "../sgx_tunittest" }
sgx_types = { path = "../sgx_types" }
#sgx_ucrypto = { path = "../sgx_ucrypto" }
sgx_unwind = { path = "../sgx_unwind" }
#sgx_urts = { path = "../sgx_urts" }
