[package]
name = "Machinelearningsampleenclave"
version = "0.9.8"
authors = ["Baidu"]

[lib]
name = "machinelearningsampleenclave"
crate-type = ["staticlib"]

[features]
default = []

[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_types = { path = "../../../sgx_types" }
sgx_tstd = { path = "../../../sgx_tstd" }
sgx_rand = { path = "../../../sgx_rand" }

[dependencies]
rusty-machine = { path = "../../../third_party/rusty-machine" }
