[package]
name = "Backtracesampleenclave"
version = "0.9.6"
authors = ["Baidu"]

[lib]
name = "backtracesampleenclave"
crate-type = ["staticlib"]

[features]
default = []

[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_types = { path = "../../../sgx_types" }
sgx_tstd = { path = "../../../sgx_tstd", features = ["backtrace"] }