[package]
name = "sgx_tkey_exchange"
version = "0.9.8"
authors = ["Baidu"]

[lib]
name = "sgx_tkey_exchange"
crate-type = ["rlib"]

[features]
default = []

[dependencies]
sgx_types = { path = "../sgx_types" }