[dependencies]
alloc = {}
panic_unwind = {}
panic_abort = {}

[dependencies.sgx_types]
path = "/root/sgx/sgx_types"
stage = 1

[dependencies.sgx_libc]
path = "/root/sgx/sgx_libc"
stage = 2

[dependencies.sgx_tkey_exchange]
path = "/root/sgx/sgx_tkey_exchange"
stage = 2

[dependencies.sgx_tservice]
path = "/root/sgx/sgx_tservice"
stage = 2

[dependencies.sgx_tse]
path = "/root/sgx/sgx_tse"
stage = 2

[dependencies.sgx_tcrypto]
path = "/root/sgx/sgx_tcrypto"
stage = 2

[dependencies.sgx_trts]
path = "/root/sgx/sgx_trts"
stage = 3

[dependencies.sgx_unwind]
path = "/root/sgx/sgx_unwind"
stage = 4

[dependencies.sgx_tdh]
path = "/root/sgx/sgx_tdh"
stage = 4

[dependencies.sgx_tseal]
path = "/root/sgx/sgx_tseal"
stage = 4

[dependencies.sgx_tprotected_fs]
path = "/root/sgx/sgx_tprotected_fs"
stage = 4

[dependencies.sgx_alloc]
path = "/root/sgx/sgx_alloc"
stage = 4

[dependencies.std]
path = "/root/sgx/xargo/sgx_tstd"
features = ["net"]
stage = 5

[dependencies.sgx_rand]
path = "/root/sgx/sgx_rand"
stage = 6

[dependencies.sgx_serialize]
path = "/root/sgx/sgx_serialize"
stage = 6

[dependencies.sgx_tunittest]
path = "/root/sgx/sgx_tunittest"
stage = 6
