[dependencies]
alloc = {}
panic_unwind = {}
panic_abort = {}

[dependencies.sgx_types]
git = "https://github.com/baidu/rust-sgx-sdk.git"
stage = 1

[dependencies.sgx_libc]
git = "https://github.com/baidu/rust-sgx-sdk.git"
stage = 2

[dependencies.sgx_tkey_exchange]
git = "https://github.com/baidu/rust-sgx-sdk.git"
stage = 2

[dependencies.sgx_tservice]
git = "https://github.com/baidu/rust-sgx-sdk.git"
stage = 2

[dependencies.sgx_tse]
git = "https://github.com/baidu/rust-sgx-sdk.git"
stage = 2

[dependencies.sgx_tcrypto]
git = "https://github.com/baidu/rust-sgx-sdk.git"
stage = 2

[dependencies.sgx_trts]
git = "https://github.com/baidu/rust-sgx-sdk.git"
stage = 3

[dependencies.sgx_tdh]
git = "https://github.com/baidu/rust-sgx-sdk.git"
stage = 4

[dependencies.sgx_tseal]
git = "https://github.com/baidu/rust-sgx-sdk.git"
stage = 4

[dependencies.sgx_alloc]
git = "https://github.com/baidu/rust-sgx-sdk.git"
stage = 4

[dependencies.std]
git = "https://github.com/baidu/rust-sgx-sdk.git"
features = ["untrusted_fs"]
stage = 5

[dependencies.sgx_rand]
git = "https://github.com/baidu/rust-sgx-sdk.git"
stage = 6

[dependencies.sgx_serialize]
git = "https://github.com/baidu/rust-sgx-sdk.git"
stage = 6

[dependencies.sgx_tunittest]
git = "https://github.com/baidu/rust-sgx-sdk.git"
stage = 6

[dependencies.sgx_tprotected_fs]
git = "https://github.com/baidu/rust-sgx-sdk.git"
stage = 4

[patch.crates-io]
libc = { git = "https://github.com/mesalock-linux/libc-sgx" }
