[package]
name = "sgx_alloc"
version = "1.0.9-preview"
authors = ["Baidu"]
repository = "https://github.com/baidu/rust-sgx-sdk"
license-file = "LICENSE"
documentation = "https://dingelish.github.io/"
description = "Rust SGX SDK provides the ability to write Intel SGX applications in Rust Programming Language."
edition = "2018"

[lib]
name = "sgx_alloc"

[features]
default = []

[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_trts = { path = "../sgx_trts" }
