[package]
name = "sgx_edl_macro"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = { version = "1.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
sgx_edl = { path = "./sgx_edl/" }

[lib]
proc-macro = true
