[package]
name = "Filesampleenclave"
version = "0.9.5"
authors = ["Baidu"]

[lib]
name = "filesampleenclave"
crate-type = ["staticlib"]

[features]
default = []

[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_tstd = { path = "../../../sgx_tstd" }
sgx_rand = { path = "../../../sgx_rand" }
sgx_serialize = { path = "../../../sgx_serialize" }

[dependencies]
sgx_rand_derive = { path = "../../../sgx_rand_derive" }
sgx_serialize_derive = { path = "../../../sgx_serialize_derive"}
