[dependencies]
alloc = {}
panic_unwind = {}
panic_abort = {}

[dependencies.sgx_types]
path = "../../../sgx_types"
stage = 1

[dependencies.sgx_libc]
path = "../../../sgx_libc"
stage = 2

[dependencies.sgx_tkey_exchange]
path = "../../../sgx_tkey_exchange"
stage = 2

[dependencies.sgx_tservice]
path = "../../../sgx_tservice"
stage = 2

[dependencies.sgx_tse]
path = "../../../sgx_tse"
stage = 2

[dependencies.sgx_tcrypto]
path = "../../../sgx_tcrypto"
stage = 2

[dependencies.sgx_trts]
path = "../../../sgx_trts"
stage = 3

[dependencies.sgx_unwind]
path = "../../../sgx_unwind"
stage = 4

[dependencies.sgx_tdh]
path = "../../../sgx_tdh"
stage = 4

[dependencies.sgx_tseal]
path = "../../../sgx_tseal"
stage = 4

[dependencies.sgx_tprotected_fs]
path = "../../../sgx_tprotected_fs"
stage = 4

[dependencies.sgx_alloc]
path = "../../../sgx_alloc"
stage = 4

[dependencies.std]
path = "../../../xargo/sgx_tstd"
stage = 5

[dependencies.sgx_rand]
path = "../../../sgx_rand"
stage = 6

[dependencies.sgx_serialize]
path = "../../../sgx_serialize"
stage = 6

[dependencies.sgx_tunittest]
path = "../../../sgx_tunittest"
stage = 6

[patch.crates-io]
libc = { git = "https://github.com/mesalock-linux/libc-sgx" }
