[package]
name = "Cryptosampleenclave"
version = "0.1.0"
authors = ["Baidu"]

[lib]
name = "Cryptosampleenclave"
crate-type = ["staticlib"]

[features]
default = []
use_std = []

[dependencies]
sgx_types = { path = "../../../sgx_types" }
sgx_trts = { path = "../../../sgx_trts" }
sgx_tcrypto = { path = "../../../sgx_tcrypto" }
