[package]
name = "Zlibsampleenclave"
version = "1.0.0"
authors = ["Baidu"]

[lib]
name = "zlibsampleenclave"
crate-type = ["staticlib"]

[features]
default = []

[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_types = { path = "../../../sgx_types" }
sgx_tstd = { path = "../../../sgx_tstd" }

[dependencies]
inflate = { path = "../../../third_party/inflate" }
libflate = { path = "../../../third_party/libflate" }
lazy_static = { version = "1.0.2", features = ["spin_no_std"] }
